spring:
  application:
    name: naming-server
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: service_discovery
      port: 27017
      host: localhost
      auto-index-creation: true
  security:
    basic:
      enabled: true
    user:
      name: sherif
      password: sherif@123
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance.prefer-ip-address: true

---
spring:
  application:
    name: naming-server
  config:
    activate:
      on-profile: production
  data:
    mongodb:
      database: service_discovery
      port: 27017
      host: localhost
      auto-index-creation: true
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance.prefer-ip-address: true