spring:
  application:
    name: naming-server
  data:
    mongodb:
      database: service_discovery
      port: 27017
      host: localhost
      auto-index-creation: true
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance.prefer-ip-address: true

#spring.security.basic.enabled=true
#spring.security.user.name=eurekauser
#spring.security.user.password=eureka!



#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.username=root
#spring.data.mongodb.password=root