server:
  port: 8085
spring:
  config:
    activate:
      on-profile: development
  application:
    name: user-service
  data:
    mongodb:
      database: user-service-db
      port: 27017
      host: localhost
      auto-index-creation: true
      # uri: mongodb+srv://<username>:<pwd>@<cluster>.mongodb.net/<db>
    redis:
      repositories:
        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    expiry:
      time: 86400
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://adam:123456@localhost:8761/eureka/
    instance:
      hostname: localhost
security-jwt-config:
  jwtIssuer: sherif-app
  jwtSecret: encryptoWearMyWorstAreaIsChoosingASecretAndWellEnoughToAllowUsGoHomeAndRestAllManForHimselfInTheCountryOfNoMansLand
  jwtExpiry: 1440

resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: count-based
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 15s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
      instances:
        user-service-breaker:
          base-config: shared

management:
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

---
server:
  port: 8085
spring:
  config:
    activate:
      on-profile: production
  application:
    name: user-service
  data:
    mongodb:
      database: user-service-db
      port: 27017
      host: localhost
      auto-index-creation: true
      # uri: mongodb+srv://<username>:<pwd>@<cluster>.mongodb.net/<db>
    redis:
      repositories:
        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    expiry:
      time: 86400
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://adams:123456@localhost:8761/eureka/
    instance:
      hostname: localhost
security-jwt-config:
  jwtIssuer: sherif-app
  jwtSecret: encryptoWearMyWorstAreaIsChoosingASecretAndWellEnoughToAllowUsGoHomeAndRestAllManForHimselfInTheCountryOfNoMansLand
  jwtExpiry: 1440

resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: count-based
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 15s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
      instances:
        user-service-breaker:
          base-config: shared

management:
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true